# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361d7efa143829098e10f9de2e387ae73ae89884a93aeec434e72c95fda354ef0d4b5a5a1716c1f3b5407bf9f363cb238254738c2dde4b9592dad6890a976990

test:
  secret_key_base: 19f3b49fe635133b2f696bff8e6f572ef367794298b960f2a4b560394b06626273cd4bdcd6bd982658b12845463e00f895d04496d29935392e1d34cde36841ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
